# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='selected_language',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='urn',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
