# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-17 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20170617_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='bot', to='bot.Subscription'),
        ),
    ]
