# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20170617_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSubscriptionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='sms', max_length=128, null=True)),
                ('urn', models.CharField(blank=True, max_length=128)),
                ('selected_language', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bot',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='selected_language',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='subscriptions',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='urn',
        ),
        migrations.AddField(
            model_name='botsubscriptionrelation',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Bot'),
        ),
        migrations.AddField(
            model_name='botsubscriptionrelation',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Subscription'),
        ),
    ]
