# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-17 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20170617_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('received_at', models.DateTimeField()),
                ('tries', models.IntegerField(default=1)),
                ('delivery_report', models.BooleanField(default=True)),
                ('bot_subcription_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotSubscriptionRelation')),
            ],
        ),
    ]
