# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-23 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_identifier',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
